### ISSUE TITLE
Checklist main TODO

### ISSUE THREAD

**Issue by WojtaS52** [AdamStef/voluntar.io#6]
## Create a repository checklist

- [x] calendar of events,
- [x] account management (registration, login, etc.),
- [x] event map,
- [x] registration for volunteering,
- [x] collecting points,
- [x] notifications,
- [x] exchanging points for benefits,
- [x] posts,
- [x] oragniasations accounts,
- [x] scoreboard,
- [x] add opinion about volunteer + calculate his/her mark,
- [x] admin account
- [ ] organisation confirms signing volunteer
- [x] ability to ban volunteer
- [x] Admin confirms organisation
- [x] KRS verification
